### ISSUE TITLE
Sigint with exit code 139 when using BiDirectional a*

### ISSUE THREAD

**Issue by ronny5423** [adar2/Maze-Solver#3]
Hi.
I'm getting sigint error with code 139 when trying to run Bidirectional a*.
Another issue I have is that IDA* visits in a lot more nodes than the maze has, for example for the example you provided in the description, if I run it with IDA*, it visits more than 13k nodes and fails to find a solution.

**Comment by adar2** [comment]
> Hi. I'm getting sigint error with code 139 when trying to run Bidirectional a*.

Try to include <unordered_map> in the Bidirectional a* cpp file. 
I didn't encounter this error myself but someone once mentioned that it worked for him.
 
 >Another issue I have is that IDA* visits in a lot more nodes than the maze has, for example for the example you provided in the description, if I run it with IDA*, it visits more than 13k nodes and fails to find a solution.

This is the expected behavior from IDA* as it iteratively deepens the search it will search the same nodes over and over, which means that on depth d+1 it will search all the previous depths until it reaches depth d+1.

**Comment by ronny5423** [comment]
Hi, thank's for your comment.
I tried to add <unordered_map> in bidirectional a* cpp file but it didn't help.
I'm attaching a copy of the file that generated this problem:
BIASTAR
5
0,3
1,1
 -1, 1, 1, 1, -1
 -1, 1, -1, 1, -1
 -1, 1, -1, 1, -1
 -1, 1, -1, -1, -1
 -1, 1, 1, 1, -1

Another question that I have is what are the cells weights? for example, if I check a regular maze problem, should each cell contains a weight of 1?

What means also the time limit, in which units it's messaured?

**Comment by adar2** [comment]
Regarding the error you mentioned before, it seems there was missing proper handling of such a short solution (2 steps) .
Please pull the update and let me know if it worked for you.

The weights represent the cost of taking a certain step, in a regular maze problem all the steps are equal (usually 1).

The time limit is used to stop the algorithm run after some time and it is given in seconds.

**Comment by ronny5423** [comment]
Hi.
This problem was solved but I found that when I ran on a maze of 50x50, the bidirectional a* exists before time limit is over and it says that it coudn't find solution in the given time while a* on the same maze can find solution within the given time. I ran bidirectional a* on 100x100 maze and it found a solution.

**Comment by adar2** [comment]
Both algorithms have their pros and cons, it really depends on your maze, starting point, and ending point.
I'm not sure what are your needs nor what you are trying to achieve, but I suggest you check which one works best for you, and use it.

**Comment by ronny5423** [comment]
I'm working on a project for my AI course in which I need to compare differeent algorithms by different messaurments on different search space sizes. I would be happy if you could explain to me what is EBF, cutoff, d/N mesaurements.

**Comment by adar2** [comment]
EBF stands for effective branching factor, which means on average how many successor nodes were spanned by each node.
Cutoff relates to the search depth we reached when we encountered a node that has no successors.
d/N is the solution depth divided by the number of expanded nodes.
